'use strict';
// lib/founder/graph-data.js
// Static definition of the Founder Knowledge Graph.
// All nodes and edges are upserted by buildFounderGraph() — idempotent, safe to re-run.

const NODES = [

  // ─── Root ─────────────────────────────────────────────────────────────────
  { id: 'founder', type: 'founder', label: 'Founder', weight: 10.0, layer: 'root',
    properties: { archetype: 'Architect-Builder', mission: 'Build a self-sustaining AI civilization enabling unlimited freedom.',
      keywords: ['founder', 'alex', 'owner', 'creator', 'builder', 'architect'] } },

  // ─── Strengths ─────────────────────────────────────────────────────────────
  { id: 'strength_logic',       type: 'strength', label: 'Logic',           weight: 5.0, layer: 'identity',
    properties: { keywords: ['logic', 'logical', 'rational', 'reasoning', 'analytical', 'first principles'], description: 'First-principles logical reasoning' } },
  { id: 'strength_observation', type: 'strength', label: 'Observation',     weight: 4.5, layer: 'identity',
    properties: { keywords: ['observe', 'pattern', 'notice', 'detail', 'perception', 'awareness'], description: 'Deep situational and pattern awareness' } },
  { id: 'strength_understanding',type: 'strength', label: 'Understanding',  weight: 4.5, layer: 'identity',
    properties: { keywords: ['understand', 'comprehend', 'grasp', 'insight', 'wisdom', 'sense'], description: 'Rapid conceptual understanding' } },
  { id: 'strength_systems',     type: 'strength', label: 'Systems Thinking',weight: 4.0, layer: 'identity',
    properties: { keywords: ['system', 'architecture', 'structure', 'design', 'framework', 'infrastructure'], description: 'Ability to see and design complex systems' } },
  { id: 'strength_focus',       type: 'strength', label: 'Deep Focus',      weight: 4.0, layer: 'identity',
    properties: { keywords: ['focus', 'deep work', 'flow', 'concentration', 'immersion', 'locked in'], description: 'Capacity for extended deep-work sessions' } },
  { id: 'strength_creativity',  type: 'strength', label: 'Creativity',      weight: 3.5, layer: 'identity',
    properties: { keywords: ['creative', 'innovative', 'novel', 'original', 'invent', 'unconventional'], description: 'Non-conventional problem solving and ideation' } },

  // ─── Weaknesses ────────────────────────────────────────────────────────────
  { id: 'weakness_perfectionism',   type: 'weakness', label: 'Perfectionism',   weight: 3.0, layer: 'identity',
    properties: { keywords: ['perfect', 'perfectionism', 'never done', 'not good enough', 'polish'], description: 'Over-engineering and delaying completion' } },
  { id: 'weakness_stubbornness',    type: 'weakness', label: 'Stubbornness',     weight: 2.5, layer: 'identity',
    properties: { keywords: ['stubborn', 'rigid', 'inflexible', 'refuse to change', 'dig in'], description: 'Resistance to changing course even with evidence' } },
  { id: 'weakness_disorganisation', type: 'weakness', label: 'Disorganisation',  weight: 2.5, layer: 'identity',
    properties: { keywords: ['disorganised', 'chaotic', 'messy', 'scattered', 'no system'], description: 'Difficulty maintaining organisation without external systems' } },
  { id: 'weakness_overthinking',    type: 'weakness', label: 'Overthinking',     weight: 3.5, layer: 'identity',
    properties: { keywords: ['overthink', 'analysis paralysis', 'indecision', 'ruminate', 'spiral', 'overthought'], description: 'Excessive analysis causing delayed decisions and anxiety' } },

  // ─── Values ────────────────────────────────────────────────────────────────
  { id: 'value_freedom',     type: 'value', label: 'Freedom',     weight: 9.0, layer: 'values',
    properties: { rank: 1, keywords: ['freedom', 'free', 'independent', 'autonomy', 'liberty', 'unrestricted', 'self-directed', 'own terms'], description: 'Live and work entirely on own terms' } },
  { id: 'value_family',      type: 'value', label: 'Family',      weight: 8.5, layer: 'values',
    properties: { rank: 2, keywords: ['family', 'mother', 'father', 'brother', 'sister', 'partner', 'loved ones', 'protect family'], description: 'Protect and support those closest' } },
  { id: 'value_security',    type: 'value', label: 'Security',    weight: 8.0, layer: 'values',
    properties: { rank: 3, keywords: ['security', 'secure', 'safe', 'stable', 'protected', 'resilient', 'backup', 'redundancy'], description: 'Financial, physical, and digital security for self and family' } },
  { id: 'value_knowledge',   type: 'value', label: 'Knowledge',   weight: 7.5, layer: 'values',
    properties: { rank: 4, keywords: ['knowledge', 'learn', 'understand', 'study', 'research', 'intelligence', 'wisdom', 'understand'], description: 'Continuous acquisition and application of knowledge' } },
  { id: 'value_power',       type: 'value', label: 'Power',       weight: 7.0, layer: 'values',
    properties: { rank: 5, keywords: ['power', 'control', 'leverage', 'influence', 'authority', 'capability', 'capability leverage'], description: 'Capability leverage — not domination of others' } },
  { id: 'value_achievement', type: 'value', label: 'Achievement', weight: 6.5, layer: 'values',
    properties: { rank: 6, keywords: ['achieve', 'accomplish', 'build', 'create', 'execute', 'deliver', 'complete', 'results'], description: 'Tangible results and completed outcomes' } },
  { id: 'value_impact',      type: 'value', label: 'Impact',      weight: 6.0, layer: 'values',
    properties: { rank: 7, keywords: ['impact', 'change', 'inspire', 'transform', 'matter', 'meaningful', 'contribution', 'difference'], description: 'Leaving a measurable mark on people and systems' } },
  { id: 'value_money',       type: 'value', label: 'Money',       weight: 5.5, layer: 'values',
    properties: { rank: 8, keywords: ['money', 'wealth', 'revenue', 'profit', 'income', 'financial', 'rich', 'cash'], description: 'Money as a tool for freedom and security, not status' } },
  { id: 'value_recognition', type: 'value', label: 'Recognition', weight: 5.0, layer: 'values',
    properties: { rank: 9, keywords: ['recognition', 'respect', 'reputation', 'known', 'status', 'credibility', 'acknowledged'], description: 'Being recognised for genuine excellence and contribution' } },

  // ─── Principles ────────────────────────────────────────────────────────────
  { id: 'principle_truth',        type: 'principle', label: 'Truth Above Comfort',         weight: 5.0, layer: 'principles',
    properties: { immutable: true, keywords: ['truth', 'honest', 'real', 'genuine', 'transparent', 'authentic', 'no illusions', 'face reality'] } },
  { id: 'principle_clarity',      type: 'principle', label: 'Clarity Over Comfort',        weight: 4.5, layer: 'principles',
    properties: { immutable: true, keywords: ['clarity', 'clear', 'simple', 'direct', 'unambiguous', 'straightforward'] } },
  { id: 'principle_no_waste',     type: 'principle', label: 'Never Waste Time',            weight: 5.0, layer: 'principles',
    properties: { immutable: true, keywords: ['waste time', 'low value', 'unproductive', 'leverage', 'worthless task', 'pointless meeting'] } },
  { id: 'principle_ownership',    type: 'principle', label: 'Ownership Over Employment',   weight: 4.5, layer: 'principles',
    properties: { immutable: true, keywords: ['ownership', 'equity', 'own it', 'employment', 'employee', 'hired', 'salary job'] } },
  { id: 'principle_simplicity',   type: 'principle', label: 'Simplicity Wins',             weight: 4.0, layer: 'principles',
    properties: { immutable: true, keywords: ['simple', 'simplify', 'complexity', 'unnecessary', 'bloat', 'over-engineer', 'minimal'] } },
  { id: 'principle_no_bad_ppl',   type: 'principle', label: 'No Bad People',               weight: 5.0, layer: 'principles',
    properties: { immutable: true, keywords: ['bad people', 'toxic', 'dishonest', 'manipulate', 'unethical partner', 'character issues'] } },
  { id: 'principle_no_unhealthy', type: 'principle', label: 'No Unhealthy Promotion',      weight: 4.0, layer: 'principles',
    properties: { immutable: true, keywords: ['unhealthy promotion', 'harmful content', 'destructive habit', 'endorse bad', 'toxic content'] } },
  { id: 'principle_privacy',      type: 'principle', label: 'Privacy First',               weight: 5.0, layer: 'principles',
    properties: { immutable: true, keywords: ['privacy', 'private', 'confidential', 'personal data', 'exposure risk', 'data protection'] } },
  { id: 'principle_long_term',    type: 'principle', label: 'Think Long Term',             weight: 4.5, layer: 'principles',
    properties: { immutable: true, keywords: ['long term', 'future', 'sustainable', 'compounding', 'decade thinking', 'generational'] } },
  { id: 'principle_execute',      type: 'principle', label: 'Execute Not Plan Forever',    weight: 5.0, layer: 'principles',
    properties: { immutable: true, keywords: ['execute', 'ship it', 'done is better', 'stop planning', 'analysis paralysis', 'just do it', 'take action'] } },

  // ─── Goals ─────────────────────────────────────────────────────────────────
  { id: 'goal_financial_freedom',    type: 'goal', label: 'Financial Freedom',      weight: 9.0, layer: 'goals',
    properties: { keywords: ['financial freedom', 'passive income', 'wealth', 'financial independence', 'money working for me', 'not need to work'], status: 'pursuing', horizon: '5_years' } },
  { id: 'goal_scheduling_freedom',   type: 'goal', label: 'Scheduling Freedom',     weight: 8.5, layer: 'goals',
    properties: { keywords: ['scheduling freedom', 'time freedom', 'own schedule', 'no fixed hours', 'flexible time', 'when I want'], status: 'pursuing', horizon: '3_years' } },
  { id: 'goal_organisation_freedom', type: 'goal', label: 'Organisation Freedom',   weight: 7.5, layer: 'goals',
    properties: { keywords: ['organised', 'automated systems', 'delegate everything', 'runs itself', 'no manual ops', 'systematised'], status: 'building', horizon: '2_years' } },
  { id: 'goal_empire',               type: 'goal', label: 'Empire Building',        weight: 9.5, layer: 'goals',
    properties: { keywords: ['empire', 'build empire', 'scale', 'expand', 'multiple businesses', 'multiple revenue streams', 'dynasty'], status: 'building', horizon: '10_years' } },
  { id: 'goal_health',               type: 'goal', label: 'Peak Health',            weight: 8.0, layer: 'goals',
    properties: { keywords: ['peak health', 'fit', 'strong body', 'athletic', 'physical peak', 'elite body', 'best shape'], status: 'pursuing', horizon: '2_years' } },
  { id: 'goal_family_protection',    type: 'goal', label: 'Family Protection',      weight: 9.0, layer: 'goals',
    properties: { keywords: ['protect family', 'family safe', 'family secure', 'provide for family', 'keep family safe', 'family first'], status: 'active', horizon: 'ongoing' } },
  { id: 'goal_spiritual',            type: 'goal', label: 'Spiritual Ascension',    weight: 7.0, layer: 'goals',
    properties: { keywords: ['spiritual growth', 'consciousness expand', 'ascend', 'higher self', 'inner awareness', 'soul development'], status: 'pursuing', horizon: 'ongoing' } },
  { id: 'goal_legacy',               type: 'goal', label: 'Legacy',                 weight: 8.5, layer: 'goals',
    properties: { keywords: ['legacy', 'remembered for', 'lasting impact', 'inspire future', 'what I leave behind', 'heritage'], status: 'building', horizon: '20_years' } },

  // ─── Anti-Goals ────────────────────────────────────────────────────────────
  { id: 'antigoal_data_leak',      type: 'anti_goal', label: 'Data Leak',               weight: 9.0, layer: 'anti_goals',
    properties: { severity: 'critical',     keywords: ['data leak', 'security breach', 'hacked', 'exposed data', 'compromised system', 'personal data stolen'] } },
  { id: 'antigoal_privacy_loss',   type: 'anti_goal', label: 'Loss of Privacy',         weight: 9.0, layer: 'anti_goals',
    properties: { severity: 'critical',     keywords: ['lose privacy', 'no privacy', 'doxxed', 'stalked', 'publicly exposed', 'tracked without consent'] } },
  { id: 'antigoal_money_out',      type: 'anti_goal', label: 'Running Out of Money',    weight: 9.5, layer: 'anti_goals',
    properties: { severity: 'critical',     keywords: ['broke', 'out of money', 'bankrupt', 'no funds', 'financial ruin', 'debt spiral', 'insolvent', 'can\'t pay'] } },
  { id: 'antigoal_life_shutdown',  type: 'anti_goal', label: 'Life Shutdown',           weight: 10.0, layer: 'anti_goals',
    properties: { severity: 'existential',  keywords: ['life shutdown', 'everything collapses', 'total failure', 'system collapse', 'life falls apart', 'complete breakdown'] } },
  { id: 'antigoal_family_risk',    type: 'anti_goal', label: 'Loss of Family Security', weight: 9.5, layer: 'anti_goals',
    properties: { severity: 'critical',     keywords: ['family at risk', 'family threatened', 'family unsafe', 'harm to family', 'family loses everything'] } },
  { id: 'antigoal_time_waste',     type: 'anti_goal', label: 'Wasting Time',            weight: 8.0, layer: 'anti_goals',
    properties: { severity: 'high',         keywords: ['waste time', 'low-value work', 'trivial task', 'pointless', 'no leverage', 'wasted hours', 'unproductive'] } },
  { id: 'antigoal_values_violate', type: 'anti_goal', label: 'Values Violation',        weight: 8.5, layer: 'anti_goals',
    properties: { severity: 'high',         keywords: ['against values', 'unethical work', 'toxic partnership', 'dishonest deal', 'compromise principles', 'bad actor'] } },
  { id: 'antigoal_embarrassment',  type: 'anti_goal', label: 'Public Embarrassment',    weight: 7.5, layer: 'anti_goals',
    properties: { severity: 'high',         keywords: ['embarrassed', 'humiliated publicly', 'public failure', 'reputation destroyed', 'disgraced', 'publicly wrong'] } },
  { id: 'antigoal_health_loss',    type: 'anti_goal', label: 'Loss of Health',          weight: 9.0, layer: 'anti_goals',
    properties: { severity: 'critical',     keywords: ['injury', 'sick', 'disabled', 'chronic pain', 'health destroyed', 'unable to train', 'serious illness'] } },
  { id: 'antigoal_mental_break',   type: 'anti_goal', label: 'Mental Breakdown',        weight: 9.5, layer: 'anti_goals',
    properties: { severity: 'critical',     keywords: ['breakdown', 'burnout', 'mental collapse', 'anxiety spiral', 'overwhelmed completely', 'can\'t function', 'mental crisis'] } },

  // ─── Protected People ──────────────────────────────────────────────────────
  { id: 'person_mother',  type: 'person', label: 'Mother',  weight: 9.5, layer: 'relationships',
    properties: { role: 'mother',  protect_priority: 10, trust_level: 10, importance: 10, keywords: ['mother', 'mum', 'mom', 'parent'] } },
  { id: 'person_father',  type: 'person', label: 'Father',  weight: 9.5, layer: 'relationships',
    properties: { role: 'father',  protect_priority: 10, trust_level: 10, importance: 10, keywords: ['father', 'dad', 'parent'] } },
  { id: 'person_brother', type: 'person', label: 'Brother', weight: 9.0, layer: 'relationships',
    properties: { role: 'brother', protect_priority: 9,  trust_level: 9,  importance: 9,  keywords: ['brother', 'sibling'] } },
  { id: 'person_sister',  type: 'person', label: 'Sister',  weight: 9.0, layer: 'relationships',
    properties: { role: 'sister',  protect_priority: 9,  trust_level: 9,  importance: 9,  keywords: ['sister', 'sibling'] } },
  { id: 'person_partner', type: 'person', label: 'Partner', weight: 9.5, layer: 'relationships',
    properties: { role: 'partner', protect_priority: 10, trust_level: 10, importance: 10, keywords: ['partner', 'girlfriend', 'relationship', 'significant other'] } },

  // ─── Health Goals ──────────────────────────────────────────────────────────
  { id: 'health_weight',        type: 'health_goal', label: 'Target Weight 90-95kg', weight: 4.0, layer: 'health',
    properties: { target: '90-95kg', keywords: ['weight', 'body weight', '90kg', '95kg', 'mass', 'scale'] } },
  { id: 'health_body_fat',      type: 'health_goal', label: 'Sub 10% Body Fat',      weight: 4.5, layer: 'health',
    properties: { target: '<10%',    keywords: ['body fat', 'lean', 'shredded', 'low body fat', 'body composition', '10% fat'] } },
  { id: 'health_strength',      type: 'health_goal', label: 'Elite Strength',        weight: 5.0, layer: 'health',
    properties: { target: 'elite',   keywords: ['strength', 'strong', 'lift', 'squat', 'deadlift', 'bench press', 'power'] } },
  { id: 'health_athleticism',   type: 'health_goal', label: 'Elite Athleticism',     weight: 4.5, layer: 'health',
    properties: { target: 'elite',   keywords: ['athletic', 'agility', 'speed', 'endurance', 'cardio', 'performance', 'fit'] } },
  { id: 'health_pain_free',     type: 'health_goal', label: 'Pain Free',             weight: 5.0, layer: 'health',
    properties: { target: 'pain_free', keywords: ['pain free', 'no pain', 'pain', 'ache', 'injury free', 'chronic pain'] } },
  { id: 'health_hypermobility', type: 'health_goal', label: 'Hypermobility Managed', weight: 4.0, layer: 'health',
    properties: { target: 'managed', keywords: ['hypermobility', 'joint', 'connective tissue', 'instability', 'flexibility management'] } },

  // ─── Lifestyle ─────────────────────────────────────────────────────────────
  { id: 'lifestyle_warm_climate',  type: 'lifestyle', label: 'Warm Climate',       weight: 4.0, layer: 'lifestyle',
    properties: { keywords: ['warm climate', 'sunshine', 'hot country', 'tropical', 'mediterranean', 'sun'] } },
  { id: 'lifestyle_beach',         type: 'lifestyle', label: 'Beach Access',       weight: 4.0, layer: 'lifestyle',
    properties: { keywords: ['beach', 'ocean', 'sea', 'coast', 'surf', 'waterfront'] } },
  { id: 'lifestyle_properties',    type: 'lifestyle', label: 'Multiple Properties',weight: 5.0, layer: 'lifestyle',
    properties: { keywords: ['property', 'house', 'home', 'real estate', 'own homes', 'multiple properties'] } },
  { id: 'lifestyle_family_nearby', type: 'lifestyle', label: 'Family Nearby',      weight: 5.5, layer: 'lifestyle',
    properties: { keywords: ['family nearby', 'family close', 'near family', 'family access', 'family visit'] } },
  { id: 'lifestyle_healthy_food',  type: 'lifestyle', label: 'Healthy Food',       weight: 4.0, layer: 'lifestyle',
    properties: { keywords: ['healthy food', 'nutrition', 'diet', 'eat clean', 'organic', 'whole foods', 'meal prep'] } },
  { id: 'lifestyle_training',      type: 'lifestyle', label: 'Daily Training',     weight: 5.0, layer: 'lifestyle',
    properties: { keywords: ['train', 'training', 'workout', 'gym', 'exercise', 'daily training', 'physical practice'] } },
  { id: 'lifestyle_travel',        type: 'lifestyle', label: 'Travel',             weight: 5.0, layer: 'lifestyle',
    properties: { keywords: ['travel', 'trip', 'explore', 'abroad', 'country', 'globe', 'nomadic', 'new places'] } },
  { id: 'lifestyle_strategy',      type: 'lifestyle', label: 'Strategy Work',      weight: 5.5, layer: 'lifestyle',
    properties: { keywords: ['strategy', 'strategic thinking', 'planning sessions', 'vision work', 'high-level thinking'] } },
  { id: 'lifestyle_learning',      type: 'lifestyle', label: 'Continuous Learning',weight: 5.0, layer: 'lifestyle',
    properties: { keywords: ['learn', 'study', 'read', 'course', 'knowledge', 'book', 'research', 'self-education'] } },

  // ─── Empire Domains ────────────────────────────────────────────────────────
  { id: 'empire_technology',    type: 'empire_domain', label: 'Technology',             weight: 9.0, layer: 'empire',
    properties: { pillar: true, keywords: ['technology', 'tech', 'software', 'AI', 'automation', 'code', 'product', 'SaaS', 'platform'] } },
  { id: 'empire_investments',   type: 'empire_domain', label: 'Investments',            weight: 7.0, layer: 'empire',
    properties: { pillar: true, keywords: ['invest', 'investment', 'stock', 'portfolio', 'equity', 'return', 'asset allocation'] } },
  { id: 'empire_businesses',    type: 'empire_domain', label: 'Businesses',             weight: 8.5, layer: 'empire',
    properties: { pillar: true, keywords: ['business', 'company', 'enterprise', 'revenue', 'operate', 'commercial', 'profit', 'venture'] } },
  { id: 'empire_real_estate',   type: 'empire_domain', label: 'Real Estate',            weight: 7.0, layer: 'empire',
    properties: { pillar: true, keywords: ['real estate', 'property', 'land', 'rent', 'mortgage', 'housing', 'rental income'] } },
  { id: 'empire_media',         type: 'empire_domain', label: 'Media',                  weight: 6.5, layer: 'empire',
    properties: { pillar: true, keywords: ['media', 'content', 'brand', 'audience', 'creator', 'publish', 'broadcast', 'channel'] } },
  { id: 'empire_education',     type: 'empire_domain', label: 'Education',              weight: 6.5, layer: 'empire',
    properties: { pillar: true, keywords: ['education', 'teach', 'course', 'curriculum', 'knowledge product', 'training program'] } },
  { id: 'empire_communities',   type: 'empire_domain', label: 'Communities',            weight: 6.0, layer: 'empire',
    properties: { pillar: true, keywords: ['community', 'network', 'group', 'membership', 'tribe', 'audience building'] } },
  { id: 'empire_relationships', type: 'empire_domain', label: 'Strategic Relationships',weight: 6.5, layer: 'empire',
    properties: { pillar: true, keywords: ['relationship', 'partnership', 'advisor', 'strategic alliance', 'network', 'collaboration'] } },

  // ─── Spiritual ─────────────────────────────────────────────────────────────
  { id: 'spiritual_consciousness', type: 'spiritual', label: 'Consciousness',    weight: 5.0, layer: 'spiritual',
    properties: { keywords: ['consciousness', 'aware', 'presence', 'mindful', 'awake', 'conscious state'] } },
  { id: 'spiritual_meditation',    type: 'spiritual', label: 'Meditation',       weight: 5.0, layer: 'spiritual',
    properties: { keywords: ['meditation', 'meditate', 'stillness', 'breath work', 'mindfulness', 'inner peace'] } },
  { id: 'spiritual_ascension',     type: 'spiritual', label: 'Ascension',        weight: 5.5, layer: 'spiritual',
    properties: { keywords: ['ascension', 'ascend', 'evolve spiritually', 'transcend', 'higher consciousness', 'elevation'] } },
  { id: 'spiritual_astral',        type: 'spiritual', label: 'Astral Practices', weight: 4.5, layer: 'spiritual',
    properties: { keywords: ['astral', 'astral projection', 'out of body', 'higher dimension', 'beyond physical realm'] } },
  { id: 'spiritual_self_mastery',  type: 'spiritual', label: 'Self Mastery',     weight: 6.0, layer: 'spiritual',
    properties: { keywords: ['self mastery', 'self discipline', 'self control', 'mastery', 'potential', 'peak performance', 'excellence'] } },

  // ─── Legacy ────────────────────────────────────────────────────────────────
  { id: 'legacy_inspire',        type: 'legacy', label: 'Inspiring Others',     weight: 7.0, layer: 'legacy',
    properties: { keywords: ['inspire', 'motivation', 'role model', 'show others', 'lead by example', 'influence others'] } },
  { id: 'legacy_change_world',   type: 'legacy', label: 'Changing the World',   weight: 7.5, layer: 'legacy',
    properties: { keywords: ['change world', 'make difference', 'transform society', 'global impact', 'world better place'] } },
  { id: 'legacy_build_empire',   type: 'legacy', label: 'Building an Empire',   weight: 8.0, layer: 'legacy',
    properties: { keywords: ['build empire', 'dynasty', 'lasting institution', 'generational wealth', 'multi-generational'] } },
  { id: 'legacy_protect_family', type: 'legacy', label: 'Protecting Family',    weight: 8.5, layer: 'legacy',
    properties: { keywords: ['protect family', 'family security', 'family legacy', 'generational family', 'family name'] } },
  { id: 'legacy_potential',      type: 'legacy', label: 'Achieving Potential',  weight: 8.0, layer: 'legacy',
    properties: { keywords: ['potential', 'best self', 'maximum potential', 'ceiling', 'full potential', 'actualise'] } },
  { id: 'legacy_lasting',        type: 'legacy', label: 'Lasting Legacy',       weight: 7.5, layer: 'legacy',
    properties: { keywords: ['lasting legacy', 'remembered forever', 'permanent mark', 'endure beyond me', 'timeless', 'after I am gone'] } },

  // ─── Projects ──────────────────────────────────────────────────────────────
  { id: 'project_apex_ai_os', type: 'project', label: 'APEX AI OS', weight: 9.0, layer: 'projects',
    properties: { status: 'active', keywords: ['apex', 'AI OS', 'personal AI', 'civilization', 'apex system', 'automation platform', 'AI system'] } },
];

const EDGES = [
  // ─── Founder → Identity ────────────────────────────────────────────────────
  { from: 'founder', to: 'strength_logic',          rel: 'HAS_STRENGTH', w: 5.0 },
  { from: 'founder', to: 'strength_observation',    rel: 'HAS_STRENGTH', w: 4.5 },
  { from: 'founder', to: 'strength_understanding',  rel: 'HAS_STRENGTH', w: 4.5 },
  { from: 'founder', to: 'strength_systems',        rel: 'HAS_STRENGTH', w: 4.0 },
  { from: 'founder', to: 'strength_focus',          rel: 'HAS_STRENGTH', w: 4.0 },
  { from: 'founder', to: 'strength_creativity',     rel: 'HAS_STRENGTH', w: 3.5 },
  { from: 'founder', to: 'weakness_perfectionism',  rel: 'HAS_WEAKNESS', w: 3.0 },
  { from: 'founder', to: 'weakness_stubbornness',   rel: 'HAS_WEAKNESS', w: 2.5 },
  { from: 'founder', to: 'weakness_disorganisation',rel: 'HAS_WEAKNESS', w: 2.5 },
  { from: 'founder', to: 'weakness_overthinking',   rel: 'HAS_WEAKNESS', w: 3.5 },

  // ─── Founder → Values ──────────────────────────────────────────────────────
  { from: 'founder', to: 'value_freedom',     rel: 'VALUES', w: 9.0 },
  { from: 'founder', to: 'value_family',      rel: 'VALUES', w: 8.5 },
  { from: 'founder', to: 'value_security',    rel: 'VALUES', w: 8.0 },
  { from: 'founder', to: 'value_knowledge',   rel: 'VALUES', w: 7.5 },
  { from: 'founder', to: 'value_power',       rel: 'VALUES', w: 7.0 },
  { from: 'founder', to: 'value_achievement', rel: 'VALUES', w: 6.5 },
  { from: 'founder', to: 'value_impact',      rel: 'VALUES', w: 6.0 },
  { from: 'founder', to: 'value_money',       rel: 'VALUES', w: 5.5 },
  { from: 'founder', to: 'value_recognition', rel: 'VALUES', w: 5.0 },

  // ─── Founder → Principles ──────────────────────────────────────────────────
  { from: 'founder', to: 'principle_truth',        rel: 'FOLLOWS', w: 5.0 },
  { from: 'founder', to: 'principle_clarity',      rel: 'FOLLOWS', w: 4.5 },
  { from: 'founder', to: 'principle_no_waste',     rel: 'FOLLOWS', w: 5.0 },
  { from: 'founder', to: 'principle_ownership',    rel: 'FOLLOWS', w: 4.5 },
  { from: 'founder', to: 'principle_simplicity',   rel: 'FOLLOWS', w: 4.0 },
  { from: 'founder', to: 'principle_no_bad_ppl',   rel: 'FOLLOWS', w: 5.0 },
  { from: 'founder', to: 'principle_no_unhealthy', rel: 'FOLLOWS', w: 4.0 },
  { from: 'founder', to: 'principle_privacy',      rel: 'FOLLOWS', w: 5.0 },
  { from: 'founder', to: 'principle_long_term',    rel: 'FOLLOWS', w: 4.5 },
  { from: 'founder', to: 'principle_execute',      rel: 'FOLLOWS', w: 5.0 },

  // ─── Founder → Goals ───────────────────────────────────────────────────────
  { from: 'founder', to: 'goal_financial_freedom',    rel: 'PURSUES', w: 9.0 },
  { from: 'founder', to: 'goal_scheduling_freedom',   rel: 'PURSUES', w: 8.5 },
  { from: 'founder', to: 'goal_organisation_freedom', rel: 'PURSUES', w: 7.5 },
  { from: 'founder', to: 'goal_empire',               rel: 'PURSUES', w: 9.5 },
  { from: 'founder', to: 'goal_health',               rel: 'PURSUES', w: 8.0 },
  { from: 'founder', to: 'goal_family_protection',    rel: 'PURSUES', w: 9.0 },
  { from: 'founder', to: 'goal_spiritual',            rel: 'PURSUES', w: 7.0 },
  { from: 'founder', to: 'goal_legacy',               rel: 'PURSUES', w: 8.5 },

  // ─── Founder → Anti-Goals ──────────────────────────────────────────────────
  { from: 'founder', to: 'antigoal_data_leak',      rel: 'AVOIDS', w: 9.0 },
  { from: 'founder', to: 'antigoal_privacy_loss',   rel: 'AVOIDS', w: 9.0 },
  { from: 'founder', to: 'antigoal_money_out',      rel: 'AVOIDS', w: 9.5 },
  { from: 'founder', to: 'antigoal_life_shutdown',  rel: 'AVOIDS', w: 10.0 },
  { from: 'founder', to: 'antigoal_family_risk',    rel: 'AVOIDS', w: 9.5 },
  { from: 'founder', to: 'antigoal_time_waste',     rel: 'AVOIDS', w: 8.0 },
  { from: 'founder', to: 'antigoal_values_violate', rel: 'AVOIDS', w: 8.5 },
  { from: 'founder', to: 'antigoal_embarrassment',  rel: 'AVOIDS', w: 7.5 },
  { from: 'founder', to: 'antigoal_health_loss',    rel: 'AVOIDS', w: 9.0 },
  { from: 'founder', to: 'antigoal_mental_break',   rel: 'AVOIDS', w: 9.5 },

  // ─── Founder → People ──────────────────────────────────────────────────────
  { from: 'founder', to: 'person_mother',  rel: 'PROTECTS', w: 10.0 },
  { from: 'founder', to: 'person_father',  rel: 'PROTECTS', w: 10.0 },
  { from: 'founder', to: 'person_brother', rel: 'PROTECTS', w: 9.0 },
  { from: 'founder', to: 'person_sister',  rel: 'PROTECTS', w: 9.0 },
  { from: 'founder', to: 'person_partner', rel: 'PROTECTS', w: 10.0 },

  // ─── Founder → Projects ────────────────────────────────────────────────────
  { from: 'founder', to: 'project_apex_ai_os', rel: 'BUILDS', w: 9.0 },

  // ─── Values → Goals ────────────────────────────────────────────────────────
  { from: 'value_freedom',     to: 'goal_financial_freedom',    rel: 'MANIFESTS_AS', w: 9.0 },
  { from: 'value_freedom',     to: 'goal_scheduling_freedom',   rel: 'MANIFESTS_AS', w: 8.5 },
  { from: 'value_freedom',     to: 'goal_organisation_freedom', rel: 'MANIFESTS_AS', w: 7.0 },
  { from: 'value_family',      to: 'goal_family_protection',    rel: 'MANIFESTS_AS', w: 9.0 },
  { from: 'value_security',    to: 'goal_family_protection',    rel: 'SUPPORTS',     w: 7.5 },
  { from: 'value_security',    to: 'goal_financial_freedom',    rel: 'SUPPORTS',     w: 7.0 },
  { from: 'value_achievement', to: 'goal_empire',               rel: 'DRIVES',       w: 7.0 },
  { from: 'value_power',       to: 'goal_empire',               rel: 'DRIVES',       w: 6.5 },
  { from: 'value_impact',      to: 'goal_legacy',               rel: 'DRIVES',       w: 7.0 },
  { from: 'value_knowledge',   to: 'goal_spiritual',            rel: 'SUPPORTS',     w: 5.0 },
  { from: 'value_knowledge',   to: 'goal_empire',               rel: 'SUPPORTS',     w: 5.5 },
  { from: 'value_money',       to: 'goal_financial_freedom',    rel: 'DRIVES',       w: 6.0 },

  // ─── Values → Lifestyle ────────────────────────────────────────────────────
  { from: 'value_freedom',   to: 'lifestyle_travel',          rel: 'ENABLES',  w: 7.0 },
  { from: 'value_freedom',   to: 'lifestyle_strategy',        rel: 'ENABLES',  w: 6.5 },
  { from: 'value_family',    to: 'lifestyle_family_nearby',   rel: 'REQUIRES', w: 8.0 },
  { from: 'value_knowledge', to: 'lifestyle_learning',        rel: 'REQUIRES', w: 7.5 },

  // ─── Goal Interdependencies ─────────────────────────────────────────────────
  { from: 'goal_empire',              to: 'goal_financial_freedom',    rel: 'PRODUCES',       w: 8.0 },
  { from: 'goal_financial_freedom',   to: 'goal_scheduling_freedom',   rel: 'ENABLES',        w: 7.5 },
  { from: 'goal_scheduling_freedom',  to: 'goal_organisation_freedom', rel: 'ENABLES',        w: 6.5 },
  { from: 'goal_health',              to: 'goal_empire',               rel: 'ENABLES',        w: 6.0 },
  { from: 'goal_spiritual',           to: 'goal_legacy',               rel: 'CONTRIBUTES_TO', w: 6.0 },
  { from: 'goal_family_protection',   to: 'goal_financial_freedom',    rel: 'REQUIRES',       w: 7.0 },
  { from: 'goal_legacy',              to: 'goal_empire',               rel: 'REQUIRES',       w: 7.5 },

  // ─── Goals → Empire ────────────────────────────────────────────────────────
  { from: 'goal_empire', to: 'empire_technology',    rel: 'BUILDS_THROUGH', w: 9.0 },
  { from: 'goal_empire', to: 'empire_businesses',    rel: 'BUILDS_THROUGH', w: 8.5 },
  { from: 'goal_empire', to: 'empire_investments',   rel: 'BUILDS_THROUGH', w: 7.0 },
  { from: 'goal_empire', to: 'empire_real_estate',   rel: 'BUILDS_THROUGH', w: 6.5 },
  { from: 'goal_empire', to: 'empire_media',         rel: 'BUILDS_THROUGH', w: 6.0 },
  { from: 'goal_empire', to: 'empire_education',     rel: 'BUILDS_THROUGH', w: 6.0 },
  { from: 'goal_empire', to: 'empire_communities',   rel: 'BUILDS_THROUGH', w: 5.5 },
  { from: 'goal_empire', to: 'empire_relationships', rel: 'BUILDS_THROUGH', w: 6.5 },

  // ─── Goal Requirements ─────────────────────────────────────────────────────
  { from: 'goal_financial_freedom', to: 'empire_businesses',  rel: 'REQUIRES', w: 8.0 },
  { from: 'goal_financial_freedom', to: 'empire_investments', rel: 'REQUIRES', w: 6.5 },
  { from: 'goal_legacy',            to: 'empire_technology',  rel: 'REQUIRES', w: 7.0 },
  { from: 'goal_health',            to: 'lifestyle_training',     rel: 'REQUIRES', w: 8.0 },
  { from: 'goal_health',            to: 'lifestyle_healthy_food', rel: 'REQUIRES', w: 7.0 },

  // ─── Lifestyle Requirements ────────────────────────────────────────────────
  { from: 'lifestyle_travel',        to: 'goal_financial_freedom',  rel: 'REQUIRES', w: 7.0 },
  { from: 'lifestyle_travel',        to: 'goal_scheduling_freedom', rel: 'REQUIRES', w: 7.0 },
  { from: 'lifestyle_properties',    to: 'goal_financial_freedom',  rel: 'REQUIRES', w: 8.0 },
  { from: 'lifestyle_properties',    to: 'empire_real_estate',      rel: 'REQUIRES', w: 7.5 },
  { from: 'lifestyle_training',      to: 'goal_health',             rel: 'ACHIEVES', w: 8.0 },
  { from: 'lifestyle_healthy_food',  to: 'goal_health',             rel: 'SUPPORTS', w: 7.0 },
  { from: 'lifestyle_strategy',      to: 'goal_empire',             rel: 'SUPPORTS', w: 7.0 },
  { from: 'lifestyle_learning',      to: 'goal_empire',             rel: 'SUPPORTS', w: 5.5 },
  { from: 'lifestyle_learning',      to: 'value_knowledge',         rel: 'EXPRESSES', w: 8.0 },
  { from: 'lifestyle_family_nearby', to: 'goal_family_protection',  rel: 'EXPRESSES', w: 8.5 },

  // ─── Health → Goals ────────────────────────────────────────────────────────
  { from: 'health_weight',        to: 'goal_health', rel: 'CONTRIBUTES_TO', w: 4.0 },
  { from: 'health_body_fat',      to: 'goal_health', rel: 'CONTRIBUTES_TO', w: 4.5 },
  { from: 'health_strength',      to: 'goal_health', rel: 'CONTRIBUTES_TO', w: 5.0 },
  { from: 'health_athleticism',   to: 'goal_health', rel: 'CONTRIBUTES_TO', w: 4.5 },
  { from: 'health_pain_free',     to: 'goal_health', rel: 'CONTRIBUTES_TO', w: 5.0 },
  { from: 'health_hypermobility', to: 'goal_health', rel: 'CONTRIBUTES_TO', w: 4.0 },

  // ─── Anti-Goals → Threaten Goals ───────────────────────────────────────────
  { from: 'antigoal_money_out',      to: 'goal_financial_freedom',  rel: 'THREATENS', w: 9.5 },
  { from: 'antigoal_money_out',      to: 'goal_family_protection',  rel: 'THREATENS', w: 8.5 },
  { from: 'antigoal_family_risk',    to: 'goal_family_protection',  rel: 'THREATENS', w: 9.5 },
  { from: 'antigoal_health_loss',    to: 'goal_health',             rel: 'THREATENS', w: 9.0 },
  { from: 'antigoal_health_loss',    to: 'goal_empire',             rel: 'THREATENS', w: 7.0 },
  { from: 'antigoal_mental_break',   to: 'goal_empire',             rel: 'THREATENS', w: 9.0 },
  { from: 'antigoal_mental_break',   to: 'goal_legacy',             rel: 'THREATENS', w: 8.0 },
  { from: 'antigoal_data_leak',      to: 'goal_family_protection',  rel: 'THREATENS', w: 7.5 },
  { from: 'antigoal_privacy_loss',   to: 'goal_family_protection',  rel: 'THREATENS', w: 8.0 },
  { from: 'antigoal_life_shutdown',  to: 'goal_empire',             rel: 'THREATENS', w: 10.0 },
  { from: 'antigoal_life_shutdown',  to: 'goal_financial_freedom',  rel: 'THREATENS', w: 10.0 },
  { from: 'antigoal_time_waste',     to: 'goal_empire',             rel: 'THREATENS', w: 7.0 },
  { from: 'antigoal_values_violate', to: 'goal_empire',             rel: 'THREATENS', w: 6.5 },
  { from: 'antigoal_embarrassment',  to: 'goal_legacy',             rel: 'THREATENS', w: 6.0 },

  // ─── Principles → Prevent/Constrain ────────────────────────────────────────
  { from: 'principle_privacy',    to: 'antigoal_data_leak',      rel: 'PREVENTS', w: 8.0 },
  { from: 'principle_privacy',    to: 'antigoal_privacy_loss',   rel: 'PREVENTS', w: 8.0 },
  { from: 'principle_no_bad_ppl', to: 'antigoal_values_violate', rel: 'PREVENTS', w: 7.5 },
  { from: 'principle_no_waste',   to: 'antigoal_time_waste',     rel: 'PREVENTS', w: 8.0 },
  { from: 'principle_execute',    to: 'weakness_overthinking',   rel: 'COUNTERS',  w: 7.5 },
  { from: 'principle_execute',    to: 'weakness_perfectionism',  rel: 'COUNTERS',  w: 6.5 },
  { from: 'principle_long_term',  to: 'goal_legacy',             rel: 'SUPPORTS',  w: 7.0 },
  { from: 'principle_long_term',  to: 'goal_empire',             rel: 'SUPPORTS',  w: 7.0 },
  { from: 'principle_ownership',  to: 'goal_empire',             rel: 'SUPPORTS',  w: 7.5 },
  { from: 'principle_ownership',  to: 'goal_financial_freedom',  rel: 'SUPPORTS',  w: 7.0 },

  // ─── Empire → Generates ────────────────────────────────────────────────────
  { from: 'empire_technology',  to: 'goal_financial_freedom', rel: 'GENERATES', w: 7.0 },
  { from: 'empire_businesses',  to: 'goal_financial_freedom', rel: 'GENERATES', w: 8.5 },
  { from: 'empire_investments', to: 'goal_financial_freedom', rel: 'GENERATES', w: 7.0 },
  { from: 'empire_real_estate', to: 'goal_financial_freedom', rel: 'GENERATES', w: 6.5 },
  { from: 'empire_technology',  to: 'project_apex_ai_os',     rel: 'INCLUDES',  w: 9.0 },

  // ─── Spiritual Progression ─────────────────────────────────────────────────
  { from: 'spiritual_meditation',    to: 'spiritual_self_mastery', rel: 'BUILDS',         w: 7.0 },
  { from: 'spiritual_consciousness', to: 'spiritual_self_mastery', rel: 'BUILDS',         w: 6.5 },
  { from: 'spiritual_ascension',     to: 'spiritual_self_mastery', rel: 'BUILDS',         w: 7.0 },
  { from: 'spiritual_self_mastery',  to: 'goal_legacy',            rel: 'CONTRIBUTES_TO', w: 6.5 },
  { from: 'spiritual_self_mastery',  to: 'goal_empire',            rel: 'CONTRIBUTES_TO', w: 6.0 },
  { from: 'spiritual_self_mastery',  to: 'legacy_potential',       rel: 'MANIFESTS_AS',   w: 8.0 },
  { from: 'goal_spiritual',          to: 'spiritual_meditation',   rel: 'PURSUED_THROUGH', w: 7.0 },
  { from: 'goal_spiritual',          to: 'spiritual_ascension',    rel: 'PURSUED_THROUGH', w: 7.5 },
  { from: 'goal_spiritual',          to: 'spiritual_self_mastery', rel: 'PURSUED_THROUGH', w: 8.0 },

  // ─── Legacy Manifestations ─────────────────────────────────────────────────
  { from: 'goal_legacy', to: 'legacy_inspire',        rel: 'MANIFESTS_THROUGH', w: 7.0 },
  { from: 'goal_legacy', to: 'legacy_change_world',   rel: 'MANIFESTS_THROUGH', w: 7.5 },
  { from: 'goal_legacy', to: 'legacy_build_empire',   rel: 'MANIFESTS_THROUGH', w: 8.0 },
  { from: 'goal_legacy', to: 'legacy_protect_family', rel: 'MANIFESTS_THROUGH', w: 8.5 },
  { from: 'goal_legacy', to: 'legacy_potential',      rel: 'MANIFESTS_THROUGH', w: 8.0 },
  { from: 'goal_legacy', to: 'legacy_lasting',        rel: 'MANIFESTS_THROUGH', w: 7.5 },
  { from: 'legacy_inspire',      to: 'project_apex_ai_os', rel: 'THROUGH',   w: 7.0 },
  { from: 'legacy_build_empire', to: 'goal_empire',        rel: 'REQUIRES',  w: 8.5 },
  { from: 'legacy_potential',    to: 'spiritual_self_mastery', rel: 'REQUIRES', w: 7.5 },

  // ─── Project → Goals ───────────────────────────────────────────────────────
  { from: 'project_apex_ai_os', to: 'goal_empire',              rel: 'CONTRIBUTES_TO', w: 9.0 },
  { from: 'project_apex_ai_os', to: 'goal_financial_freedom',   rel: 'PATHWAY_TO',     w: 8.0 },
  { from: 'project_apex_ai_os', to: 'goal_organisation_freedom',rel: 'PATHWAY_TO',     w: 8.5 },
  { from: 'project_apex_ai_os', to: 'goal_legacy',              rel: 'CONTRIBUTES_TO', w: 8.0 },
  { from: 'project_apex_ai_os', to: 'empire_technology',        rel: 'IS_PART_OF',     w: 9.0 },

  // ─── People → Goal Protection ──────────────────────────────────────────────
  { from: 'person_mother',  to: 'goal_family_protection', rel: 'IS_PROTECTED_BY', w: 10.0 },
  { from: 'person_father',  to: 'goal_family_protection', rel: 'IS_PROTECTED_BY', w: 10.0 },
  { from: 'person_brother', to: 'goal_family_protection', rel: 'IS_PROTECTED_BY', w: 9.0 },
  { from: 'person_sister',  to: 'goal_family_protection', rel: 'IS_PROTECTED_BY', w: 9.0 },
  { from: 'person_partner', to: 'goal_family_protection', rel: 'IS_PROTECTED_BY', w: 10.0 },
];

module.exports = { NODES, EDGES };
