-- Migration 022: Executive Performance Engine v2
-- Extends executive_performance with decision tracking, calibration, and value measurement.
-- Adds exec_performance_stats cache table and exec_status_reports for batch reports.

-- Extend existing executive_performance table
ALTER TABLE executive_performance
  ADD COLUMN IF NOT EXISTS decision_type  TEXT    DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS category       TEXT    DEFAULT 'strategic',
  ADD COLUMN IF NOT EXISTS value_created  FLOAT,
  ADD COLUMN IF NOT EXISTS calibration_error FLOAT,
  ADD COLUMN IF NOT EXISTS context_summary TEXT;

-- decision_type: approved | rejected | executed | pending
-- calibration_error: confidence_at_time - actual_outcome (1.0 if matched, 0.0 if not)
-- Positive = overconfident for this row; negative = underconfident.

CREATE INDEX IF NOT EXISTS idx_exec_perf_decision ON executive_performance(decision_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_exec_perf_category ON executive_performance(category, entity_id);

-- Cached computed stats per executive. Rebuilt on each computeAllStats() call.
CREATE TABLE IF NOT EXISTS exec_performance_stats (
  id                      TEXT        PRIMARY KEY,
  entity_id               TEXT        UNIQUE NOT NULL,
  total_recommendations   INT         NOT NULL DEFAULT 0,
  with_outcome            INT         NOT NULL DEFAULT 0,
  matched                 INT         NOT NULL DEFAULT 0,
  accuracy                FLOAT,
  avg_confidence          FLOAT,
  avg_impact_score        FLOAT,
  total_value_created     FLOAT       NOT NULL DEFAULT 0,
  mean_calibration_error  FLOAT,
  brier_score             FLOAT,
  calibration_label       TEXT,
  computed_at             TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Batch status reports generated by generateStatusReport()
CREATE TABLE IF NOT EXISTS exec_status_reports (
  id              TEXT        PRIMARY KEY,
  report          JSONB       NOT NULL DEFAULT '{}',
  generated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_exec_status_gen ON exec_status_reports(generated_at DESC);
