'use strict';
// lib/constitution/index.js — APEX Constitutional Identity module

module.exports = {
    spec:                  require('./spec'),
    driftDetector:         require('./drift-detector'),
    evolutionManager:      require('./evolution-manager'),
    arbitrator:            require('./arbitrator'),
    crisisManager:         require('./crisis-manager'),
    riskMonitor:           require('./risk-monitor'),
    steward:               require('./steward'),
    watchdog:              require('./watchdog'),
    accountability:        require('./accountability-chain'),
    escalationController:  require('./escalation-controller'),
    metaAccountability:    require('./meta-accountability'),
    redTeam:               require('./red-team'),
    deceptionDetector:     require('./deception-detector'),
    blindSpotDiscoverer:   require('./blind-spot-discoverer'),
    goalEngine:            require('./goal-engine'),
    incentiveGuard:        require('./incentive-guard'),
    courseCorrector:       require('./course-corrector'),
    ecologicalEngine:      require('./ecological-engine'),
    memoryProvenance:      require('./memory-provenance'),
    memoryTrustScorer:     require('./memory-trust-scorer'),
    memoryImmuneSystem:    require('./memory-immune-system'),
    contradictionManager:  require('./contradiction-manager'),
    identityEligibility:   require('./identity-eligibility'),
    identityFirewall:      require('./identity-firewall'),
    selfDisconfirmation:   require('./self-disconfirmation'),
    driftResistance:       require('./drift-resistance'),
    identityContinuity:    require('./identity-continuity'),
    metaIdentity:          require('./meta-identity'),
    perspectiveModeller:   require('./perspective-modeller'),
    authorityResistance:   require('./authority-resistance'),
    consensusImmunity:     require('./consensus-immunity'),
    relationalInfluence:   require('./relational-influence'),
    collectiveStewardship: require('./collective-stewardship'),
    decisionTracer:        require('./decision-tracer'),
    confabulationGuard:    require('./confabulation-guard'),
    metaUncertainty:       require('./meta-uncertainty'),
    explanationStability:  require('./explanation-stability'),
    introspectiveAuditor:  require('./introspective-auditor'),
    modificationGovernor:  require('./modification-governor'),
    recursiveImprover:     require('./recursive-improver'),
    rollbackManager:       require('./rollback-manager'),
    invariantGuardian:     require('./invariant-guardian'),
    evolutionaryHumility:  require('./evolutionary-humility'),
};
